# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e37768f214d3b131ba3a4ded16495cc5a6d571117a417900ee59f03aa07651d6b87cfe23f8f1235652a6cded5656afcdd2b29ad3d5b0284473b8417a02d49d0

test:
  secret_key_base: de66176103069764d5067b9fa8c00ee2fb2264f45eee332a08d1e85f7d8f4250b34fd750f2d9d63b10401e80c02410497e3aac521b2652d03dbdb6a4231da46d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
